### ISSUE TITLE
Feature Request: Custom fan controls

### ISSUE THREAD

**Issue by songsaree** [exelban/stats#814] opened 2022-01-27 15:07 UTC
First of all, thank you so much for developing the app. It is simpler and better to use than any monitoring app.

Currently, I use an app called <max fan control> to manage the temperature of my MacBook. STATS also has a fan control feature, but it is regrettable that it does not have a function to customize in a specific temperature.

Ex) <macs fan control> has a custom function that causes the fan to start when the cpu temperature set as shown in the picture is reached.

![image](https://user-images.githubusercontent.com/81437617/151385047-af101899-60cc-4df9-9ae1-a51f0a8ef19b.png)

**Details:**
 - Device: [MBP m1]
 - macOS: [12.0.1]
 - Application version: [2.7.1]

**Comment by exelban** [comment] 2022-01-27 18:01
Duplicate of #564

**Closed by exelban** 2022-01-27 18:01 UTC
