### ISSUE TITLE
Interface unknown when connected to VPN

### ISSUE THREAD

**Issue by specter78** [exelban/stats#514] opened 2021-06-22 05:48 UTC
**Describe the bug**
When using vpn (I'm using Passepartout), interface, network and physical address are shown as unknown.

**Details:**
 - Device: Macbook Pro 2015
 - MacOS 11.4
 - Application version 2.5.20

**Comment by exelban** [comment] 2021-06-22 11:33
Duplicate of #448

**Closed by exelban** 2021-06-22 11:33 UTC
