### ISSUE TITLE
Feature request: The same icon order every launch.

### ISSUE THREAD

**Issue by szerli** [exelban/stats#566] opened 2021-08-01 12:31 UTC
**Describe the bug**
I would love to see every time I open up application the same icon order and let user customise it, for e.g. battery icon first, then CPU and RAM. 

**Details:**
 - Device: Macbook Pro 13 2015 Early
 - MacOS: 11.4
 - Application version: 2.6.2

**Comment by exelban** [comment] 2021-08-01 12:41
Duplicate of #503

**Closed** 2021-08-01 12:40 UTC
