### ISSUE TITLE
@VCoves  Have you managed to solve your problem? Why did you close the issue?

### ISSUE THREAD

**Issue by VCoves** [exelban/stats#963] opened 2022-06-09 10:49 UTC
I'm replying to your comment below since that issue is comment restricted to collaborators. 

I fixed it by enabling the "HID sensors" on Sensors -> Module Settings. 
On a different note I think something isn't quite right, since it detects only 2 efficiency cores temps, and 7 performance cores, instead of 4 ef + 4 perf.
<img width="272" alt="Screenshot 2022-06-09 at 12 46 30" src="https://user-images.githubusercontent.com/32782704/172829557-9ce95bfe-bae6-405c-80e0-555e6861db66.png">
 
----------------------------------------------------------------------------------

@VCoves  Have you managed to solve your problem? Why did you close the issue?

_Originally posted by @Helios69 in https://github.com/exelban/stats/issues/958#issuecomment-1150963804_

**Comment by VCoves** [comment] 2022-06-09 10:51
@Helios69

**Comment by exelban** [comment] 2022-06-09 10:51
Duplicate of #944

**Closed by exelban** 2022-06-09 10:51 UTC
