### ISSUE TITLE
[feature request] disk I/O per app

### ISSUE THREAD

**Issue by Stooovie** [exelban/stats#912] opened 2022-04-19 10:32 UTC
Hi, I enjoy Stats very much, the only thing that keeps me using iStatMenus is that they are the only stats app I know that shows disk I/O throughput per app. As a video editor who deals with enormous files and storage bandwidths, this is often important to me, to investigate bottlenecks, hang apps and so on. Can something like that be added to Stats? Thanks!

![Screenshot 2022-04-19 at 12 31 00](https://user-images.githubusercontent.com/10572373/163985191-779a2782-b1e9-4399-9219-91c1a6060e0d.jpg)
?

**Comment by exelban** [comment] 2022-04-21 09:26
Duplicate of #494

**Closed by exelban** 2022-04-21 09:26 UTC
