### ISSUE TITLE
Suggestion: Expandable combined modules

### ISSUE THREAD

**Issue by nsa-twell** [exelban/stats#1449] opened 2023-05-05 09:36 UTC
Good morning. Great program. Suggestion rather than issue:

If clicking on a combined module tile, show the full module tile for that module. That way we could get the best of both worlds.

(Atlhough at the same time my wish is to balance this with the desire to keep such utilities as this one as lightweight as possible.)

**Comment by exelban** [comment] 2023-05-06 15:48
Duplicate of #1353

**Closed by exelban** 2023-05-06 15:48 UTC
