### ISSUE TITLE
Refresh battery information regularly

### ISSUE THREAD

**Issue by XInTheDark** [exelban/stats#1355] opened 2023-03-12 11:09 UTC
**Describe the bug**
Battery related information, specifically "low power mode", is not refreshed.

Steps to reproduce:
1. Open battery popup
2. Enable low power mode in settings
3. Check the popup - the other stats are refreshing, but the low power mode still shows "Disabled".

**Details:**
 - Device: MacBook Air M1, 2020
 - macOS: 12.0
 - Application version: 2.8.11 (latest)

**Comment by exelban** [comment] 2023-03-12 16:40
Duplicate of #1264

**Closed by exelban** 2023-03-12 16:40 UTC
