### ISSUE TITLE
process not responding when clicking the menu bar

### ISSUE THREAD

**Issue by hungrysnake** [exelban/stats#597] opened 2021-08-30 05:54 UTC
**Describe the bug**
os just boot up and the meter in menubar showing high cpu. activity monitor shows the process is not responding. restarting the app still showing the same result. reboot machine doesn't help.

notice that it happened after the recent update. haven't tried to run the older version yet.

![image](https://user-images.githubusercontent.com/42885440/131291546-d76dc7ae-5dd4-4df6-9c9d-c4850c298525.png)

**Details:**
 - Device: iMac mid 2010
 - MacOS 10.13.6
 - Application version can't see because the app is not responding.

**Comment by exelban** [comment] 2021-08-30 13:13
Duplicate of #571

**Closed by exelban** 2021-08-30 13:13 UTC
