### ISSUE TITLE
CPU, RAM 1%

### ISSUE THREAD

**Issue by cristiean** [exelban/stats#527] opened 2021-07-04 23:52 UTC
CPU and RAM 1% after update

To note, I installed Bartender 4 today and am using their width-reduction feature, bringing all of the menu bar items closer together (as can be seen in the image). Not sure whether that impacts Stats in any way. When I quit Bartender, they're still on 1%.

 I have also used the new alignment features in Stats.

**Details:**
 - Device: [e.g. Macbook Pro 2018]
 - MacOS [e.g. 11.4]
 - Application version [e.g. 2.5.22]
<img width="416" alt="Screenshot 2021-07-05 at 00 43 47" src="https://user-images.githubusercontent.com/24500712/124402931-3ce67300-dd2b-11eb-9a06-1ed6431ca7b3.png">

**Comment by ysomad** [comment] 2021-07-05 05:55
Same
<img width="663" alt="Screenshot 2021-07-05 at 12 55 49 PM" src="https://user-images.githubusercontent.com/49870662/124423932-540b7c00-dd90-11eb-867e-7e6ba10160d0.png">

**Comment by exelban** [comment] 2021-07-05 07:00
Duplicate of #525

**Closed by exelban** 2021-07-05 07:00 UTC
