### ISSUE TITLE
[BUG] Energy saving indicator doesn't update on power input change

### ISSUE THREAD

**Issue by pesaventofilippo** [exelban/stats#1481] opened 2023-05-22 17:36 UTC
**Describe the bug**
The Battery widget has an option to color the battery orange if the power saving mode is active.
In the latest versions, it seems to only update when Stats is launched. For example, if I activate power saving mode and then start Stats, it works, but if I then deactivate power saving Stats still thinks it's on, until I quit the app and reopen it.

It also happens when not manually switching, for example I have power saving set to enabled when on battery and disabled when charging, and if I plug or unplug the cable, the icon on Stats doesn't change.

**Details:**
 - Device: MacBook Pro 2018, 13'
 - macOS: Ventura 13.4
 - Application version: 2.8.22

**Comment by exelban** [comment] 2023-05-22 17:40
Duplicate of #1459

**Closed by exelban** 2023-05-22 17:40 UTC
