### ISSUE TITLE
[Feature request] Export Settings

### ISSUE THREAD

**Issue by mjr2595** [exelban/stats#1122] opened 2022-10-16 19:42 UTC
It would be super awesome if we had the option to export our settings. I like to play around with theming and being able to quickly export/import settings is very helpful. Also helpful when setting up a new computer.

...Unless I'm just not seeing this option and it already exists.

**Comment by mjr2595** [comment] 2022-10-16 19:42
commenting just to say thanks for all your hard work. Love this application!

**Comment by exelban** [comment] 2022-10-16 22:10
Duplicate of #1093

**Closed by exelban** 2022-10-16 22:10 UTC

**Comment by mjr2595** [comment] 2022-10-16 22:22
Ah thanks for pointing out the previous request. For anyone else seeing this, here's a [link](https://github.com/exelban/stats/issues/801#issuecomment-1020517746) to a previous request on how you can find/export the settings.
