### ISSUE TITLE
Fan menu widget displays with white background until clicked after switching displays

### ISSUE THREAD

**Issue by stewartadam** [exelban/stats#158] opened 2020-11-13 20:57 UTC
**Describe the bug**
When connecting/disconnecting an external monitor, the fan widget sometimes shows up in a white box until clicked.

**Details:**
 - Device: Macbook Pro 2016 15"
 - MacOS 10.15.7
 - Application version 2.4.2

screenshot:
![image](https://user-images.githubusercontent.com/77808/99120409-a99bda00-25af-11eb-8510-fde8c8bf7f0b.png)

**Comment by exelban** [comment] 2020-11-13 21:02
Duplicate of #125

**Closed by exelban** 2020-11-13 21:02 UTC
