### ISSUE TITLE
FEATURE REQUEST: Add composite View

### ISSUE THREAD

**Issue by ravero** [exelban/stats#576] opened 2021-08-06 12:21 UTC
One thing that I particularly like about iStat Menu is the ability to have a composite view of all the available monitors. I just want to have the gauge for the CPU usage on the menu, but when I click on it I would like to be able to have access to the other views.

**Comment by exelban** [comment] 2021-08-07 08:19
Duplicate of #528

**Closed by exelban** 2021-08-07 08:19 UTC
