### ISSUE TITLE
Sensors widget dispeared

### ISSUE THREAD

**Issue by org0000h** [exelban/stats#349] opened 2021-02-18 04:08 UTC
**Describe the bug**
Sensors widget dispeared

**Details:**
 - Device: Macbook Pro 2019 16inch
 - MacOS 11.2.1
 - Application version 2.5.0

**Comment by tpgone** [comment] 2021-02-18 04:45
Same here. 
v2.5.0 is not showing icons in menubar, app window opens when launched.

Reverted back to v2.4.16 and that shows all icons.

**Comment by exelban** [comment] 2021-02-18 08:19
Duplicate of #346

**Closed by exelban** 2021-02-18 08:19 UTC
