### ISSUE TITLE
Status bar disappears after a few minutes

### ISSUE THREAD

**Issue by jherrera123** [exelban/stats#459] opened 2021-05-05 14:06 UTC
After starting the app, wait a few minutes and then the status icons disappears. This behavior started happening after upgrading to the latest version `2.5.12`.

I have to relaunch the application manually to see the icons again, then the app will crash again after a few more minutes.

OS: MacOS 10.15.7

**Comment by exelban** [comment] 2021-05-05 14:18
Duplicate of #453

**Closed by exelban** 2021-05-05 14:18 UTC
