### ISSUE TITLE
The year of my Mac is wrong

### ISSUE THREAD

**Issue by mushi007** [exelban/stats#1005] opened 2022-07-18 03:08 UTC
**Describe the bug**
The year of my Mac is wrong.

<img width="572" alt="pic1@2x" src="https://user-images.githubusercontent.com/13403033/179439466-d435629f-402b-4408-a96b-14d32acd4206.png">
<img width="713" alt="pic2@2x" src="https://user-images.githubusercontent.com/13403033/179439474-b11ca062-bb32-4f4b-b8e2-77498e888f7d.png">

**Details:**
 - Device: Macbook Pro 2019, 15-inch
 - macOS: 12.4
 - Application version: 2.7.26

**Comment by exelban** [comment] 2022-07-18 06:37
Duplicate of #923

**Closed by exelban** 2022-07-18 06:37 UTC
