### ISSUE TITLE
Menubar spacing issue

### ISSUE THREAD

**Issue by davidebretti** [exelban/stats#757] opened 2021-12-19 10:08 UTC
Hi,
I would like to report an issue with elements spacing in the menubar, if I add a consistent number of elements I get them too much spaced, therefore sometimes I cannot see all of them.
Tried to reproduce the issue in a scientific way to see if there's a pattern but couldn't find any, could be also a macOS related issue.
Please check my screenshots, with 5 elements spacing is correct, adding another one (or also changing the layout having a graph) make spacing wrong.
Thank you for your support and your amazing work.

<img width="479" alt="Screen01" src="https://user-images.githubusercontent.com/63709762/146671123-ca738201-dfb5-4021-8073-63a983a29c94.png">
<img width="664" alt="Screen02" src="https://user-images.githubusercontent.com/63709762/146671128-6f7b1c01-94bb-40b9-ac25-f0709cba8c7d.png">

 - Device: Macbook Pro 14'' 2021
 - macOS: 12.1
 - Application version: 2.6.23

**Comment by exelban** [comment] 2021-12-19 11:25
Duplicate of #731

**Closed by exelban** 2021-12-19 11:25 UTC

**Comment by davidebretti** [comment] 2021-12-19 12:13
(thanks, sorry I didn't notice the duplicate)
