### ISSUE TITLE
Doesn't know what kind of Mac I'm using. 

### ISSUE THREAD

**Issue by Kaamoz** [exelban/stats#998] opened 2022-07-12 20:27 UTC
Currently using 2010 Mac Pro. Thinks im using a 2012 Mac Pro and uses picture of 2013 Trash Can Ma
![Screen Shot 2022-07-12 at 3 26 40 PM](https://user-images.githubusercontent.com/109178537/178588949-53f48995-cd34-4108-a26f-3dbf78298678.png)
c

**Comment by exelban** [comment] 2022-07-13 19:35
Duplicate of #923

**Closed by exelban** 2022-07-13 19:35 UTC
