### ISSUE TITLE
[Feature Request] Option to toggle on/off the Battery Low Power Mode

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [exelban/stats#1475] opened 2023-05-19 11:21 UTC
It would be great to have the option to simply turn on/off the Battery Low Power Mode within the Battery stats. Currently, you have to go to the Preference to change this. 

<img width="586" alt="image" src="https://github.com/exelban/stats/assets/5219339/20d3754b-890e-42d9-b629-7c162f523bf9">

**Comment by exelban** [comment] 2023-05-21 18:38
Duplicate of #1024

**Closed by exelban** 2023-05-21 18:38 UTC
