### ISSUE TITLE
High CPU usage after menu gets stuck

### ISSUE THREAD

**Issue by cedric2446** [exelban/stats#611] opened 2021-09-06 15:59 UTC
When app stops responding the cpu usage will spike and when you click the buttons of stats in het menu bar it won't disappear.
The CPU usage will spike to about 70-90% on an M1 MacBook Air and reach -+90°C.

 - Device: MacBook Air M1  2020 16GB 
 - MacOS 12
 - Application version 2.6.8

**Comment by exelban** [comment] 2021-09-06 16:01
Duplicate of #606

**Closed by exelban** 2021-09-06 16:01 UTC
