### ISSUE TITLE
Inaccurate CPU readings

### ISSUE THREAD

**Issue by kim0** [exelban/stats#230] opened 2020-12-16 14:52 UTC
**Describe the bug**
The attached screenshot shows `WindowServer` is consuming 18%, while the total is showing as only 14%. So something is off in the CPU consumption calculations.

**Details:**
 - Device: Macbook Pro 2013
 - MacOS 11.0.1
 - Application version 2.4.8

<img width="281" alt="inaccurate-reading" src="https://user-images.githubusercontent.com/59667/102364297-f44daf00-3fbe-11eb-948e-c332138eb287.png">

**Comment by exelban** [comment] 2020-12-16 15:02
Duplicate of #115

**Closed by exelban** 2020-12-16 15:02 UTC

**Comment by kim0** [comment] 2020-12-16 15:11
Thanks @exelban .. But I am not comparing against Activity Monitor, or another tool. This app "stats" gives a breakdown of readings, which when added up, are more than the show total. I'm guessing that's a different issue ?

**Comment by exelban** [comment] 2020-12-16 15:45
Process usage has Unix style.
Total usage has a "0 - 100%" style.
