### ISSUE TITLE
Issues with 2.5.22 (Apple silicon)

### ISSUE THREAD

**Issue by PriZmRL** [exelban/stats#532] opened 2021-07-07 23:53 UTC
The last update have broke more than few components of the app, see the picture

The SSD, RAM, CPU and GPU % are stuck at 1, however, the graphs are still working
<img width="253" alt="Screen Shot 2021-07-08 at 2 50 03 AM" src="https://user-images.githubusercontent.com/37186463/124842117-889d5480-df97-11eb-9832-6db843b7c365.png">

**Comment by exelban** [comment] 2021-07-08 06:49
Duplicate of #525

**Closed by exelban** 2021-07-08 06:49 UTC
