### ISSUE TITLE
Network Chart does not remember color settings

### ISSUE THREAD

**Issue by mhtawfiq** [exelban/stats#1080] opened 2022-09-11 11:56 UTC
**Describe the bug**
After setting the color of download and upload fr the Network Cart widget, when you restart Stats the color settings are forgotten and the chart uses the default colors again.

**Details:**
 - Device: Macbook Pro 2016
 - macOS: 10.15.1
 - Application version: 2.7.34

**Comment by exelban** [comment] 2022-09-11 17:00
Hi. Thanks for reporting.
As I can notice it looks like the colors are saved. But reversed (upload and download). I cannot reproduce that colors are reset.

**Comment by mhtawfiq** [comment] 2022-09-12 12:14
Hi

I just double checked and your observation is correct. The download/upload colors are saved but reversed on Stats app restart.

Thank you.

**Comment by exelban** [comment] 2022-09-12 13:09
Thanks. Will be fixed.

**Closed** 2022-09-18 11:20 UTC
Labels: Need to be fixed

**Comment by mhtawfiq** [comment] 2022-09-18 11:44
Thank you! I just tested 2.7.35 and the issue is fixed now.
