### ISSUE TITLE
Program hangs when clicked on either RAM or CPU symbol

### ISSUE THREAD

**Issue by nowakommunikation** [exelban/stats#640] opened 2021-09-21 10:10 UTC
The program hangs as soon as I click on the RAM or CPU symbol to check what they say. All other symbols work fine and open up a dialog with the image (battery etc.) and stats. 
When the program hangs, the CPU usage goes to 100 % for it (according to Activity Monitor) and I can only force quit it.

**Details:**
 - Device: MacBook Pro 6,2 Mid 2010
 - macOS 10.13.6]
 - Application version 2.6.11

**Comment by exelban** [comment] 2021-09-21 10:12
Duplicate of #611

**Closed by exelban** 2021-09-21 10:12 UTC
