### ISSUE TITLE
Feature request: fan control based on sensors

### ISSUE THREAD

**Issue by niczky12** [exelban/stats#564] opened 2021-07-28 16:25 UTC
Would it be possible to set fan speed based on the temp sensors? So if the CPU temp increases, increase speed of fan too in a linear manner?

**Comment by exelban** [comment] 2021-07-28 16:27
Duplicate of #513

**Comment by exelban** [comment] 2021-07-28 16:28
I have a plan to combine Sensors and Fans modules. And make it possible. But it will be not in the near future for sure.

**Closed by exelban** 2021-07-28 16:28 UTC
