### ISSUE TITLE
Bluetooth monitor: battery level is missing in the widget

### ISSUE THREAD

**Issue by chenshanb3** [exelban/stats#1091] opened 2022-09-19 09:28 UTC
Hello, I am very happy to have such a software that can visually check the system status. I would like to make a suggestion. When I was using it recently, I found that this Bluetooth monitor can only display a single power level. I hope it can display all the power levels. It displays 2 lines by default. If there are more than two, I hope it can be scrolled. Thanks!

<img width="322" alt="image" src="https://user-images.githubusercontent.com/96278502/190987928-a31b1943-895d-4cf5-91b7-68aa33681c0f.png">

**Comment by exelban** [comment] 2022-09-19 09:55
Please ensure that you have the latest version of the app.

**Comment by chenshanb3** [comment] 2022-09-20 08:24
<img width="756" alt="image" src="https://user-images.githubusercontent.com/96278502/191207013-cfba4878-5c3f-448e-973c-064141b7f36f.png">

latest version of the app

**Comment by exelban** [comment] 2022-09-20 09:37
Hmm, looks like #1083 is not fixed. Will take a look again.

**Comment by chenshanb3** [comment] 2022-09-20 09:53
The keyboard and mouse identifiers are recognized as one

<img width="563" alt="image" src="https://user-images.githubusercontent.com/96278502/191227023-6070fe0c-9f47-49e2-9da5-cdc486941297.png">

**Comment by exelban** [comment] 2022-09-20 10:27
The bug is in the popup view. It does not remove the missing level.

**Comment by exelban** [comment] 2022-09-20 21:00
update: the problem is not in the popup view. But in the Sensors widgets. The bug appears after sensor widgets receive the option to sort the items. And it uses the key as id. And battery level keys could be repeated in many devices. Will be fixed.

**Closed** 2022-09-25 02:04 UTC
Labels: bug
