### ISSUE TITLE
[Feature Request] Show aggregated top processes per app

### ISSUE THREAD

**Issue by idr4n** [exelban/stats#1137] opened 2022-10-27 07:50 UTC
Thanks for a really cool app. I am using it right now to replace iStat Menus as I like the design of your menu icons better and the slightly better performance than iStats.

One suggestion of a feature that I would love to have in your app is to show the top processes in the CPU and RAM modules as aggregated by app rather than individual processes (as an app can be running several processes). I just find it more informative that way.

This is a comparison between the two apps:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/20104703/198222077-5c4d6c7a-770c-4512-82ad-4313adfd37ee.png">

For example, Chrome is showing several helper processes, so it is difficult to know how much the total of Chrome is with all its processes combined.

Thanks again!

**Comment by exelban** [comment] 2022-10-27 16:49
Hi. I have described why it's not quite possible at least for now.
Duplicate of #674

**Closed by exelban** 2022-10-27 16:49 UTC
