### ISSUE TITLE
Sensor widget font is not same with other

### ISSUE THREAD

**Issue by shensmart** [exelban/stats#183] opened 2020-11-23 05:52 UTC
Thanks for the great app.

I updte Stats from 2.3.8 to 2.4.4. But I found the font of sensor is not same with others. It looks like bold font. 

2.3.8
![image](https://user-images.githubusercontent.com/6029260/99932385-d1025c00-2d92-11eb-8f8a-4d007b5daf39.png)

2.4.4
![image](https://user-images.githubusercontent.com/6029260/99932391-d3fd4c80-2d92-11eb-9811-bebc4a40ed06.png)

**Comment by exelban** [comment] 2020-11-23 08:34
Duplicate of #161

**Closed by exelban** 2020-11-23 08:34 UTC
