### ISSUE TITLE
Battery widget's low power mode doesn't update until Stats is restarted

### ISSUE THREAD

**Issue by skylon07** [exelban/stats#1459] opened 2023-05-08 19:47 UTC
**Describe the bug**
When I switch low power mode on/off, the battery widget's "Low power mode:" row doesn't update to reflect the change. However, if I restart Stats, the value will update to the correct state on startup. Here's a little recording of me demonstrating this on my poor almost-dead mac:

https://user-images.githubusercontent.com/4754387/236918788-3b129d30-33a6-4b4a-9d01-3888bf70d91d.mov

**Details:**
<img width="698" alt="Screen Shot 2023-05-08 at 13 44 37" src="https://user-images.githubusercontent.com/4754387/236918371-42d71d07-0612-4a81-9786-f7056d2383aa.png">
Using Stats Version 2.8.20

**Comment by exelban** [comment] 2023-05-09 06:43
Duplicate of #1279

**Closed** 2023-05-09 06:44 UTC
