### ISSUE TITLE
Temperature sensor metric background is sometimes rendered wrong

### ISSUE THREAD

**Issue by stekostas** [exelban/stats#151] opened 2020-11-10 07:09 UTC
**Describe the bug**

The temperature sensor metric background is _sometimes_ rendered wrong.

![image](https://user-images.githubusercontent.com/1971808/98640840-0e92ce00-232b-11eb-8f86-b60bfa47cca4.png)

Unfortunately, I have not found a reliable way of reproducing the issue; it seems to be happening randomly. The `General > Appearance` preference on the machine is set to `Dark`. Here are my settings for the metric:

![image](https://user-images.githubusercontent.com/1971808/98641004-5ca7d180-232b-11eb-8da2-2f04c2a8641f.png)

**Details:**
 - Device: Macbook Pro 2020
 - MacOS 10.15.7 (19H15)
 - Application version 2.4.2

**Comment by exelban** [comment] 2020-11-10 07:16
Duplicate of #125

**Closed by exelban** 2020-11-10 07:16 UTC
