### ISSUE TITLE
Feature request: M1 - bundle CPU temp sensors and show only highest (like "Hot" app)

### ISSUE THREAD

**Issue by ximmox** [exelban/stats#601] opened 2021-08-31 08:47 UTC
Hi, 

I really love Stats and I would like to suggest a little feature that makes me use the "Hot" app (source and info: https://github.com/macmade/Hot) for showing the CPU-temperature currently instead of using Stats for it.

<img width="476" alt="Bildschirmfoto 2021-08-31 um 10 34 53" src="https://user-images.githubusercontent.com/2152145/131471143-3cc31ccb-91de-4334-8002-d04d5745dfc4.png">

Hot reads out all the relevant CPU temp sensors on the M1, which seem to be the eACC and pACC MTU Temp Sensors with different numbers (like in the screenshot).
For the menubar icon, it only shows the highest temperature value of those, which is the most relevant info for the user I suppose.
I don't care which core is how hot currently, I would like to see with a glance what's the highest my overall CPU is at the moment.

Maybe it is possible to add some kind of "sensor bundling"? For example make a virtual sensor, which shows the highest temp of X chosen sensors you want to be monitored.
Or, more simply: add a sensor-entry like "show only highest CPU temp" in the sensors menu.

Please let me know if there is any more info that I can provide or if I can test anything on my MacBook Air.

Thanks!

**Comment by exelban** [comment] 2021-08-31 10:30
Duplicate of #473

**Closed by exelban** 2021-08-31 10:30 UTC

**Comment by ximmox** [comment] 2021-08-31 10:49
How stupid of me to miss that, sorry! I searched for issues with "temp", "temperature" and so on and #473 didn't come up.
