### ISSUE TITLE
CPU % in top processes is out of bound by long process name

### ISSUE THREAD

**Issue by wtchangdm** [exelban/stats#1667] opened 2023-10-26 05:21 UTC
**Describe the bug**
Hi, first of all, thanks for the this awesome tool!

I recently noticed that the CPU % in top processes became out of bound because of the relatively long process name like this:

![](https://i.imgur.com/3GZHXnB.png)

I think it could be reproduced by changing an arbitrary binary to very long name.

Please let me know if further information is needed. Thanks!

**Details:**
 - Device: Macbook Pro 2023
 - macOS: 14.1
 - Application version: 2.9.10

**Comment by rajaryan12123** [comment] 2023-10-28 20:06
However long the name is, I think the percentage number should still be visible with the current implementation of processView() 🤔

I tried keeping the process name to be very long, but still the percentage seems to be present. Help me reproduce this bug.

<img width="277" alt="Screenshot 2023-10-29 at 1 32 23 AM" src="https://github.com/exelban/stats/assets/133625389/f507bf5e-244b-4e8b-9de0-00899923d3a6">

**Comment by wtchangdm** [comment] 2023-10-29 05:51
Hmm, I think another requirement here is to get over 100% per process.

A simple way to reproduce:

```go
# veryveryveryveryveryveryveryveryveryverylong.go
package main

func main() {
	hold := make(chan interface{})

	for i := 0; i < 2; i++ {
		go func () {
			for {}
		} ()
	}

	<- hold
}
```

Then `$ go run ./veryveryveryveryveryveryveryveryveryverylong.go`

![](https://i.imgur.com/zKHoI53.jpg)

**Comment by exelban** [comment] 2023-10-29 09:46
@wtchangdm thanks for that. I have been trying to reproduce that bug for a long time but cannot find a reason why it's presenting. In my case, it is always with the docker process.

Will be fixed.

**Comment by exelban** [comment] 2023-10-29 09:49
it does not work for me, for some reason(

<img width="265" alt="Zrzut ekranu 2023-10-29 o 10 48 50" src="https://github.com/exelban/stats/assets/13332412/a266bc5f-08ce-4e68-86eb-451cc890efd3">

**Comment by wtchangdm** [comment] 2023-10-29 09:56
@exelban 
Thanks for the fast reply! I tried with two processes that are > 100% but still observed the same issue.

(Not sure why the screenshot is so huge than OP, I will just leave a link here)
https://i.imgur.com/eAxyZxv.png

**Closed** 2023-11-05 17:08 UTC
Labels: Need to be fixed
