### ISSUE TITLE
CPU and RAM at 1% on Menubar

### ISSUE THREAD

**Issue by JWandscheer** [exelban/stats#530] opened 2021-07-06 14:41 UTC
Since the last Update to v2.5.22, the CPU and RAM usage is always 1% in the Menubar. In the corresponding detail-Windows the usage seems to be shown correctly.

MacBook Pro 13" 2019
2.4 GHz i5
8GB RAM
MacOS 11.4

On a MacMini 2018 (same MacOS Version, same stats version) the usage is shown correctly in the menubar.

![IMG_4122](https://user-images.githubusercontent.com/5305887/124619405-ebe49500-de78-11eb-9f43-6dd67b69cebb.jpeg)
![IMG_4121](https://user-images.githubusercontent.com/5305887/124619426-f010b280-de78-11eb-9285-348780843b19.jpeg)

**Comment by exelban** [comment] 2021-07-06 15:24
Duplicate of #525

**Closed by exelban** 2021-07-06 15:24 UTC
