### ISSUE TITLE
Can't view dropdown while in another app's fullscreen mode

### ISSUE THREAD

**Issue by coxjc** [exelban/stats#41] opened 2020-06-23 18:00 UTC
I'm not terribly sure if this is fixable or not, but if I'm in fullscreen mode for another app (e.g. Slack), I see nothing when I click on a `stats` icon. It appears to open the dropdown on the desktop that doesn't host a fullscreen app.

**Comment by exelban** [comment] 2020-06-23 18:28
@coxjc Hi. I check this, but I cannot reproduce this problem.
Do you use an external display?

What os version and mac do you have?

**Comment by coxjc** [comment] 2020-06-24 03:46
yeah, i do use two external displays but i also found it occurring when disconnected from both monitors. 

i am running Catalina 10.15.5 on a 15" MBP.

**Comment by coxjc** [comment] 2020-06-24 03:49
actually i found something somewhat odd:

if i am using an external display to the left of my MBP and i click on Stats in the external monitor, the dropdown pops up in the top left of the MBP native display

**Comment by exelban** [comment] 2020-06-24 09:37
yeap, I reproduce this bug. I will fix it in the next release (in a few days).

**Comment by exelban** [comment] 2020-06-24 15:23
Please confirm if it fixed in the new version [v2.1.0](https://github.com/exelban/stats/releases/tag/v2.1.0).

**Comment by coxjc** [comment] 2020-06-24 19:24
@exelban it looks like that release is missing the .dmg

**Comment by exelban** [comment] 2020-06-24 19:25
ohh, forgot. Added.

**Comment by coxjc** [comment] 2020-06-24 23:38
looks good. thank you sir

**Closed** 2020-06-25 07:19 UTC
Labels: bug

**Comment by FallBright6** [comment] 2025-10-06 14:01
This issue came up again on my computer. It's a 16" M1 Pro MacBook Pro running macOS 26.0.1
