### ISSUE TITLE
Mac M1: Can we exclude purgeable space in disk calculation

### ISSUE THREAD

**Issue by rmkanda** [exelban/stats#1269] opened 2023-01-18 07:04 UTC
**Bug**
In the new Mac M1 Pro, Disk is shown full always, eventhough there is space available on the disk. Please refer the below screenshots.
Can we exclude purgeable space in disk calculation?

<img width="273" alt="image" src="https://user-images.githubusercontent.com/38713281/213105231-1fd48480-94a9-4cf8-8940-600570829c9c.png">

About Mac -> Storage
<img width="575" alt="image" src="https://user-images.githubusercontent.com/38713281/213105353-d3c802f8-a4b8-4077-9ad4-9e77fef282b6.png">

Disk Utility:

<img width="802" alt="image" src="https://user-images.githubusercontent.com/38713281/213105470-fde2ca91-9adf-42ec-8205-b316a9b780f7.png">

**Details:**
 - Device: MacBook Pro (16-inch, 2021)  Apple M1 Pro
 - macOS: 12.6.1 (21G217)
 - Application version: 2.8.4

**Comment by exelban** [comment] 2023-01-18 10:47
Duplicate of #1189

**Closed by exelban** 2023-01-18 10:47 UTC
