### ISSUE TITLE
Update won't install

### ISSUE THREAD

**Issue by janericster** [exelban/stats#847] opened 2022-02-18 22:18 UTC
Update downloads but won't install. 2.7.2 > 2.7.5

MacBook Pro 16 2021 M1 Max
Monterey 12.2.1

Update prompt appears, I click download...it goes to 100% and then I click Install but nothing happens. Dialog box just stays there with no change.

**Comment by exelban** [comment] 2022-02-18 22:30
Duplicate of #828

**Closed by exelban** 2022-02-18 22:30 UTC
