### ISSUE TITLE
Battery widget kind of broken in monterey 12.5.1 on macbook air m1

### ISSUE THREAD

**Issue by pyriand3r** [exelban/stats#1048] opened 2022-08-22 12:18 UTC
As far as i can tell this appeared after installing the 12.5.1 update on my m1. The battery icon is now orange (see screenshot), regardless of the battery state. As you can see, i have disable coloring of the icon, but that settings does not take any effect any more.

In the context-menu the battery icon went completely black.

<img width="1209" alt="image" src="https://user-images.githubusercontent.com/2619815/185919337-d0c60046-c144-4ee0-a9e9-b87c8842fcbd.png">

**Details:**
 - Device: [e.g. Macbook Pro 2016]
 - macOS: [e.g. 10.15.5]
 - Application version: [e.g. 2.1.11]

**Comment by exelban** [comment] 2022-08-22 12:46
Duplicate of #1046

**Closed by exelban** 2022-08-22 12:46 UTC
