### ISSUE TITLE
How to display all stats from one icon?

### ISSUE THREAD

**Issue by asyba** [exelban/stats#719] opened 2021-11-26 00:32 UTC
How I can view many stats with just 1 icon from menu bar?

Similar like iStat Menus
![image](https://user-images.githubusercontent.com/1466530/143510434-8512f37a-fb6f-43fb-a3ad-d3be105b39fa.png)

**Comment by exelban** [comment] 2021-11-26 10:20
Duplicate of #576

**Closed by exelban** 2021-11-26 10:20 UTC
