### ISSUE TITLE
Unable to see bluetooth device list in settings

### ISSUE THREAD

**Issue by wencczhu** [exelban/stats#866] opened 2022-03-07 04:10 UTC
macOS version: 12.2.1 
Stats version: 2.7.6

I can't see the list of paired bluetooth devices in the settings
<img width="726" alt="Screen Shot 2022-03-06 at 11 05 47 PM" src="https://user-images.githubusercontent.com/100637405/156966324-959b2ba6-bd00-4bad-919b-744b89f23f74.png">

This is what the status bar look like
<img width="189" alt="Screen Shot 2022-03-06 at 11 05 59 PM" src="https://user-images.githubusercontent.com/100637405/156966362-f1049e16-5b8e-43dc-bac2-fd9c7c09e811.png">

I think I have granted bluetooth permission to the app
<img width="642" alt="Screen Shot 2022-03-06 at 11 06 28 PM" src="https://user-images.githubusercontent.com/100637405/156966391-71b01b27-b81c-44a0-9301-048ddb2a5495.png">

Btw, I don't see this issue with my other mac (mini)

**Comment by exelban** [comment] 2022-03-07 16:57
Hi. Thanks for the feedback.
If you don't see any BLE device it could be because of:
- there is no paired devices
- there is no device's that  battery level could be obtained

**Comment by Th0m4** [comment] 2022-03-08 17:19
Hi, 
I have the same problem ! 
Did you know on wich devices the battery level can be obtained ?
I have Airpods 2, MX masted and MX keys paired and connected to my macbook but nothing in the settings

**Comment by exelban** [comment] 2022-03-09 07:41
Hi. This thread is a duplicate of #859 
Please continue there.

**Closed by exelban** 2022-03-09 07:41 UTC
