### ISSUE TITLE
Battery Low Power Mode value is displayed wrong

### ISSUE THREAD

**Issue by Drallas** [exelban/stats#1279] opened 2023-01-25 08:36 UTC
**Low Power Mode shows Disabled**
Low Power Mode always shows the Disabled state, but this not matching the system value.

<img width="667" alt="Screenshot 2023-01-25 at 09 24 21" src="https://user-images.githubusercontent.com/24792888/214516175-6b96bcdb-7df6-4bfa-8524-ff71f8c71d82.png">

**Details:**
 - Device: [e.g. Macbook Air M1 2021]
 - macOS: [13.2 (22D49)]
 - Application version: [Version 2.8.5]

**Comment by exelban** [comment] 2023-01-25 18:02
Duplicate of #1264

**Closed by exelban** 2023-01-25 18:02 UTC
