### ISSUE TITLE
Second GPU is not displayed correctly

### ISSUE THREAD

**Issue by finnrobinanders** [exelban/stats#217] opened 2020-12-07 21:00 UTC
I have a 2019 Macbook Pro with Big Sur. It came with a built in Intel UHD Graphics 630 and an AMD Radeon Pro 5300M.
I would like to display the AMD GPU usage in the menu bar, not the Intel GPU. Unfortunately, the app settings only allow the selection of the option to show the Intel GPU. The AMD GPU _does_ periodically show up in the app settings and can be selected but soon after, the app switches back to the Intel GPU and the option for the AMD GPU is gone.
The AMD GPU _does_ show up in the menu bar drop down under GPU but it usually has a red dot next to it's name and displays 32˚F and 0% usage. That is obviously incorrect.

So, the AMD GPU is displaying incorrect values (along with a red dot) and, most of the time, the app does not recognize the AMD GPU as an option to display in the menu bar.

<img width="293" alt="Screen Shot 2020-12-07 at 12 57 50 PM" src="https://user-images.githubusercontent.com/67494580/101404835-0d05e880-388c-11eb-8740-dc36f6fe22a3.png">
<img width="721" alt="Screen Shot 2020-12-07 at 12 58 14 PM" src="https://user-images.githubusercontent.com/67494580/101404859-11ca9c80-388c-11eb-9f97-d1e172dc012d.png">

**Comment by exelban** [comment] 2020-12-07 22:22
Duplicate of #173

**Closed by exelban** 2020-12-07 22:22 UTC
