### ISSUE TITLE
Can we see the "real memory" instead of "memory" in the memory usage?

### ISSUE THREAD

**Issue by andyy0123** [exelban/stats#1074] opened 2022-09-06 03:27 UTC
**Describe the bug**
As the title, the **real memory** is the actual info I want to see.
This tool is really cool and helpful. Thanks to all the developer again.

![image](https://user-images.githubusercontent.com/28136658/188540818-80f3fc5b-738b-4acb-ad55-30c2f1f00154.png)

**Details:**
 - Device: Macbook Pro 2016
 - macOS: 12.5.1
 - Application version: 2.7.30

**Comment by exelban** [comment] 2022-09-06 08:19
Duplicate of #853

**Closed by exelban** 2022-09-06 08:19 UTC
