### ISSUE TITLE
[Feature request] Show graph for battery level and add timestamps in graphs

### ISSUE THREAD

**Issue by paz10s** [exelban/stats#978] opened 2022-06-21 02:14 UTC
It would be really nice if there is a graph for the battery level so it's easier to monitor how much battery I've drained in the past few hours. Below is a screenshot from iStat Menus which precisely shows the battery level.

![image](https://user-images.githubusercontent.com/65367607/174701324-a6fcdea0-3cf9-4270-ac95-a47b972088b1.png)

I'm aware that there is an existing wattage graph for power, but it would be helpful if there is one also for the battery level.

Also, for the existing graphs, timestamps can be added along the x axis, or just show the timestamp whenever you hover over the graph, just like the screenshot above.

**Comment by exelban** [comment] 2022-06-22 17:42
Duplicate of #250

**Closed by exelban** 2022-06-22 17:42 UTC
