### ISSUE TITLE
Occasional crashes

### ISSUE THREAD

**Issue by igorkulman** [exelban/stats#491] opened 2021-05-23 12:26 UTC
**Describe the bug**
Occasionally I notice the app missing from the menu bar, usually after sleep. Attaching crash logs.

**Details:**
 - Device: Macbook Pro 16" 2019
 - MacOS 11.3.1
 - Application version 2.5.1

Crash logs: [crashlogs.zip](https://github.com/exelban/stats/files/6528062/crashlogs.zip)

**Comment by exelban** [comment] 2021-05-23 12:51
Duplicate of #485.
Small notice: you provide an app version `2.5.1` but both crash reports are `2.5.15`.

**Closed by exelban** 2021-05-23 12:51 UTC
