### ISSUE TITLE
Sensors Bug in MacOS Ventura 13.0.1

### ISSUE THREAD

**Issue by Moncoutiej** [exelban/stats#1176] opened 2022-11-15 14:09 UTC
**I upgrade my MacBook Pro M1 14' to Ventura 13.0.1 yesterday and from the update I can't see the sensors icon from the menu bar**
The weird thing here is that when I open the sensor details from the weird icon in the menu bar, all the sensor values appear but the menu icon remains the same. 

**Details:**
 - Device: MacBook Pro M1 14'
 - macOS: Ventura 13.0.1
 - Application version: 2.7.43

<img width="283" alt="image" src="https://user-images.githubusercontent.com/65337792/201938544-165cece4-b661-46ff-96ff-1181dd505582.png">

**Comment by exelban** [comment] 2022-11-15 14:18
Duplicate of #1172

**Closed by exelban** 2022-11-15 14:18 UTC
