### ISSUE TITLE
External SSD is shown when disconnected long ago

### ISSUE THREAD

**Issue by richardtop** [exelban/stats#723] opened 2021-11-26 21:59 UTC
**Describe the bug**
External SSD is shown when disconnected long ago, as on the screenshot:
<img width="280" alt="s" src="https://user-images.githubusercontent.com/8013017/143657686-51732eb0-dad3-4364-9324-3b3db09c6300.png">

Related to #180 
**Details:**
 - Device: Macbook Pro 16 2019
 - macOS: 12.0.1 (21A559)
 - Application version: Version 2.6.20

**Comment by exelban** [comment] 2021-11-27 12:23
Duplicate of #664 
There is a debug version of Stats that will collect some logs.

**Closed by exelban** 2021-11-27 12:23 UTC
