### ISSUE TITLE
White Background in menu bar under some widgets

### ISSUE THREAD

**Issue by wfrank21** [exelban/stats#155] opened 2020-11-12 08:06 UTC
I'm seeing a white background under some widgets sometimes. It comes and goes. It seems to be mostly happening while the widget resizes itself. It's not exclusive to fanspeed.
![image](https://user-images.githubusercontent.com/73826476/98912227-163aaa00-24c6-11eb-9b60-d6566e44692e.png)

**Details:**
 - Device: MacBook Pro 2017, 13inch, 4 Thunderbolt Ports
 - MacOS 10.15.7
 - Application version 2.4.2

**Comment by exelban** [comment] 2020-11-12 08:15
Duplicate of #125.

**Closed by exelban** 2020-11-12 08:15 UTC
