### ISSUE TITLE
Dashboard shows wrong MacBook year

### ISSUE THREAD

**Issue by kanadgodse** [exelban/stats#1001] opened 2022-07-14 19:43 UTC
**Describe the bug**
The dashboard shows MacBook Air 13" (Early 2015) on my 2017 MacBook Air.

![Screenshot 2022-07-15 at 1 08 11 AM](https://user-images.githubusercontent.com/8666523/179070199-73b591e7-7dc5-452d-9a8e-7803a92ea306.png)

**Details:**
 - Device: MacBook Air 2017
 - macOS: Monterey 12.14
 - Application version: 2.7.25

**Comment by exelban** [comment] 2022-07-14 20:19
Duplicate of #923

**Closed by exelban** 2022-07-14 20:19 UTC
