### ISSUE TITLE
[Feature Request] Dynamic fan speeds

### ISSUE THREAD

**Issue by albas99** [exelban/stats#921] opened 2022-04-27 13:43 UTC
Description: A setting where someone can set multiple different fan speeds depending on the CPU temperature/load. Similar to how istat menus and iStatistica does it. This could be based on the average CPU core temperature or open-ended for the user to choose which temperature it should be based on.

**Comment by exelban** [comment] 2022-04-28 09:24
Duplicate of #564

**Closed by exelban** 2022-04-28 09:24 UTC
