### ISSUE TITLE
wrong total network usage if using VPN

### ISSUE THREAD

**Issue by triarkya** [exelban/stats#549] opened 2021-07-19 08:53 UTC
When I'm connected via VPN, the total traffic throughput displayed seems to be about twice the real traffic most of the time. 
Probably because programs that establish a VPN connection are seen as separate programs, which is perfectly correct in itself.
In this case, I was connected via [Tunnelblick](https://github.com/Tunnelblick/Tunnelblick) (OpenVPN). 
I don't know how it runs over the system's internal VPN configurations, since I don't have any configurations to test for that. 

![bugImage](https://user-images.githubusercontent.com/19290639/126131112-04488fe0-455e-42a6-a54b-f2428919d283.jpeg)

**Details:**
 - Device: [Macbook Pro 2018]
 - MacOS [11.4]
 - Application version [2.6.1]

**Comment by exelban** [comment] 2021-07-19 09:31
Duplicate of #296

**Closed by exelban** 2021-07-19 09:31 UTC
