### ISSUE TITLE
Enabling different sensors values, change the background to white

### ISSUE THREAD

**Issue by jcconca** [exelban/stats#125] opened 2020-10-26 07:37 UTC
In some cases, enabling sensors to be visualised, like "Voltage", make the background of the sensor section white, and imposible to read the value.

See the below screenshots, to more information:
![Screenshot 2020-10-26 at 08 35 20](https://user-images.githubusercontent.com/8432547/97145341-5b40ab80-1766-11eb-96d2-957350f7410a.png)

After selecting values in voltage:
![Screenshot 2020-10-26 at 08 35 46](https://user-images.githubusercontent.com/8432547/97145392-6bf12180-1766-11eb-9fe6-3af1a3bcf9b0.png)

**Comment by exelban** [comment] 2020-10-30 21:37
Hi.

Thanks for reporting. Unfortunately, I do not know why it's happening. There is no any colorizing in code. 
Maybe someone could help with this. It's happening randomly on some systems. And I cannot reproduce this behavior.

**Comment by exelban** [comment] 2020-11-08 18:51
Hi.
I think I know where is the problem. But it requires rewriting the widgets. I already started to do this. Must be ready till the next release.

**Comment by entee55** [comment] 2020-11-08 21:33
I think this issue is also with dark mode. For example in dark mode the graph background colors change to white. When you have the white option selected in colors, then it is the same as the background color.
<img width="203" alt="Képernyőfotó 2020-11-08 - 22 30 41" src="https://user-images.githubusercontent.com/73840407/98484815-45c18c00-2212-11eb-8c0f-df4fc47798d4.png">
<img width="190" alt="Képernyőfotó 2020-11-08 - 22 31 29" src="https://user-images.githubusercontent.com/73840407/98484816-4823e600-2212-11eb-8e56-ef053691e063.png">

**Comment by exelban** [comment] 2020-11-08 22:43
> I think this issue is also with dark mode. For example in dark mode the graph background colors change to white. When you have the white option selected in colors, then it is the same as the background color.
> <img alt="Képernyőfotó 2020-11-08 - 22 30 41" width="203" src="https://user-images.githubusercontent.com/73840407/98484815-45c18c00-2212-11eb-8c0f-df4fc47798d4.png">
> <img alt="Képernyőfotó 2020-11-08 - 22 31 29" width="190" src="https://user-images.githubusercontent.com/73840407/98484816-4823e600-2212-11eb-8e56-ef053691e063.png">

If the problem is not related to the issue please open a separate issue. 
In this case, I don't see any problems at all. You chose a white color option. And what you expect, that it will change to the black?

PS. If you want to have monochrome colors, there is a special one. Called monochrome.

**Comment by entee55** [comment] 2020-11-08 22:56
I understand your point, I thought the same.  I meant, that in this case maybe the problem is with the background color is changing due to dark mode. I just wanted to help this issue. For me it is working as expected.

**Comment by exelban** [comment] 2020-11-11 10:11
@entee55 hi. Could I ask you to check this build?
To fix this issue, I must rewrite the sensors widget. And as you remember the last time it crashes the app(
I just don't want to repeat that situation (when the app crashes).

[Stats.dmg.zip](https://github.com/exelban/stats/files/5523339/Stats.dmg.zip)

**Comment by exelban** [comment] 2020-11-15 12:27
Fixed in the [last](https://github.com/exelban/stats/releases/tag/v2.4.3) version.

**Closed by exelban** 2020-11-15 12:27 UTC
Labels: Need to be fixed, help wanted
