### ISSUE TITLE
Modifiable localization in app settings

### ISSUE THREAD

**Issue by ppizarror** [exelban/stats#400] opened 2021-04-02 17:14 UTC
Currently, it's not possible to change the language of the app through any means; it uses the default's OS lang. Something like:

![image](https://user-images.githubusercontent.com/12925256/113437767-a322c900-93bd-11eb-9c7b-00684cf70524.png)

**Comment by exelban** [comment] 2021-04-03 08:26
Duplicate of #365

**Closed by exelban** 2021-04-03 08:26 UTC
