### ISSUE TITLE
M1 core/gpu sensor naming

### ISSUE THREAD

**Issue by yitwail** [exelban/stats#702] opened 2021-11-16 17:24 UTC
**Describe the bug**
Under Sensors, it omits cores and lists cores that aren't there.

**Details:**
 - Device: M1 Macbook Air 2020
 - macOS: 11.6.1
 - Application version: 2.6.19
 
So M1 has 4 efficiency cores and 4 performance cores, but the Sensors tab lists 2 efficiency cores and 7 performance cores. I'm just displaying Hottest CPU temperature, which I assume is accurate, but it would be nice if the cores listed matched the cores in the chip. Regardless, thanks for creating a great app.

**Comment by exelban** [comment] 2021-11-16 18:26
Duplicate of #700

**Closed by exelban** 2021-11-16 18:26 UTC
