### ISSUE TITLE
White background on sensors icon and mixed up icons with other application icons

### ISSUE THREAD

**Issue by osavchenko** [exelban/stats#147] opened 2020-11-08 15:55 UTC
**Describe the bug**
I got a white background for the sensors icon and when I click on that icon background get back to the normal state, but later it gets a white background again.
Also, as you can see from the screenshot, Stats icons mixed with other applications icon.
All theese described things got on the current version it wasn't on the previous ones.

![image](https://user-images.githubusercontent.com/617002/98469867-cb314600-21ea-11eb-9904-13b175545097.png)

**Details:**
 - Device: MacBook Pro 16" (Late 2019)
 - MacOS 10.15.7 (19H15)
 - Application version 2.4.2

P.S.: Thank you for your work 😉

**Comment by exelban** [comment] 2020-11-08 18:48
Duplicate of #125.

**Closed** 2020-11-08 18:48 UTC
