### ISSUE TITLE
Incorrect Memory and Disk Space values

### ISSUE THREAD

**Issue by TheAlexTanasescu** [exelban/stats#1308] opened 2023-02-08 06:46 UTC
**Describe the bug**
The Disk Space and Memory aren't showing the correct values, please fix this as I really loved this app until now

**Details:**
 - Device: Macbook Air M1 2020
 - macOS: Ventura 13.0.1
 - Application version: 2.8.7
<img width="288" alt="Screenshot 2023-02-07 at 11 45 08 PM" src="https://user-images.githubusercontent.com/22565432/217454773-655a7899-872c-4ede-b698-6955f0647f09.png">
<img width="481" alt="Screenshot 2023-02-07 at 11 45 26 PM" src="https://user-images.githubusercontent.com/22565432/217454776-f7f8b394-4464-4853-801e-17922dd39e8f.png">

**Comment by exelban** [comment] 2023-02-08 15:48
Duplicate of #1189

**Closed by exelban** 2023-02-08 15:48 UTC
