### ISSUE TITLE
Disk speed widget update interval

### ISSUE THREAD

**Issue by Tai-Zhou** [exelban/stats#182] opened 2020-11-23 05:39 UTC
The update interval of the speed widget (4th widget) of disk is controlled by setting "update interval" (shown as "更新间隔" in the picture),
<img width="832" alt="label" src="https://user-images.githubusercontent.com/21986946/99931564-f5106e00-2d8f-11eb-9d2b-d9e633c08d1b.png">
but this setting disappears when you actually choose the speed widget.
<img width="832" alt="speed" src="https://user-images.githubusercontent.com/21986946/99931565-f6da3180-2d8f-11eb-8975-9861151542f6.png">

**Details:**
 - Device: [MacBook Pro 13" (Mid 2019)]
 - MacOS [11.0.1]
 - Application version [2.4.4]

**Comment by exelban** [comment] 2020-11-24 15:16
Hi. Sorry for the long response.
Yeap, it not a bug and it's not missing. Because for bandwidth (read/write) there must be no option to change the update interval. It must be always 1 second. For more information take a look [this](https://github.com/exelban/stats/issues/113) issue.

But I noticed an interesting bug. When you switch to the speed widget (read/write). This reader must automatically switch to 1 second update interval. Now it's not ready. And the user cannot see the actual read/write stats.

**Comment by exelban** [comment] 2020-11-24 15:16
Sorry, misclick)

**Comment by Tai-Zhou** [comment] 2020-11-25 04:16
I see, and thank you for your great app!

**Comment by exelban** [comment] 2020-11-29 11:54
Fixed in the [last](https://github.com/exelban/stats/releases/tag/v2.4.5) release.

**Closed by exelban** 2020-11-29 11:54 UTC
Labels: Need to be fixed
