### ISSUE TITLE
[Bug Report] Fan Manual Control

### ISSUE THREAD

**Issue by AShortcuts** [exelban/stats#1473] opened 2023-05-19 03:25 UTC
After every update of Stats, the manual control of my fan stops working. I am on thee latest version of Stats and macOS thus far and am using a MacBook Air 2018 (Intel). It fixes when I remove the fan helper and reinstall it. If you need more information, let me know. Thanks

**Comment by f2sky** [comment] 2023-05-21 01:31
I had the same problem with the Intel MacBook, every time the fan control function failed, the way to solve it was to restart the app.

**Comment by rmilkowski** [comment] 2023-05-22 09:11
Same issue on Mac Studio and Ventura 13.4 - adjusting fan speeds stopped working for sometime now (on recent betas and now on 13.4 too). Restarting app did not help. Uninstalling fan helper and then installing it again fixed the issue.

**Comment by exelban** [comment] 2023-05-22 09:25
duplicate of #1462

**Closed by exelban** 2023-05-22 09:25 UTC
