### ISSUE TITLE
Cannot change the widget view settings in menubar

### ISSUE THREAD

**Issue by rishabhgupta03** [exelban/stats#968] opened 2022-06-15 19:07 UTC
**bug**
The modules show various widget view chart/graph options for different modules but none of them seem to be working for me and the only option available is to have numerical representation of modules. Tried reinstalling as well but nothing seems to be working. It was available on my previous mac but when i upgraded my mac to different hardware, I cannot use these charts anymore
<img width="536" alt="image" src="https://user-images.githubusercontent.com/44132253/173904908-b1feba5a-5f0c-4153-a1cc-22ecd0c827ad.png">

**Details:**
 - Device: [MacBook Pro 16" (Late 2019)
 - macOS: macOS Monterey (12.4.0)
 - Processor : Intel Core i7-9750H 2.60GHz
                                      6 cores, 12 threads
 - Application version: 2.7.21

**Comment by exelban** [comment] 2022-06-18 17:30
Duplicate of #897

**Closed by exelban** 2022-06-18 17:30 UTC
