### ISSUE TITLE
[Feature request] Kill switch

### ISSUE THREAD

**Issue by p0pcat** [exelban/stats#764] opened 2021-12-28 16:40 UTC
Please make a kill or copy pid option when right clicking on the process from menubar

**Comment by exelban** [comment] 2021-12-29 11:54
Duplicate of #569 

I could say that this option (kill process) will be added. I must to make a few changes before, and cannot give any deadlines for this feature.

**Closed by exelban** 2021-12-29 11:54 UTC

**Comment by movy** [comment] 2022-05-27 13:15
Any plans to make this work for any process, not just locked?
There's a tiny util called MiniUsage, which honestly has been a lifesaver on MacOS, as it allows me kill ANY cpu-hungry process, and it saves hours of battery life daily... w/o this feature Stats is useless tbh, what's the point of observing Chrome Helper or Tradingview eating my resources in the background w/o being able to do anything with it? 

<img width="598" alt="image" src="https://user-images.githubusercontent.com/4336560/170706362-8128ed9b-3a66-47a5-8214-88da1cfc80e1.png">
