### ISSUE TITLE
Feature Request:  Icon location persistence

### ISSUE THREAD

**Issue by tlove004** [exelban/stats#363] opened 2021-02-25 23:18 UTC
If icons are arranged to my liking, then Stats is quit and reloaded, all active modules appear at the leftmost location. 

Arranged:
<img width="354" alt="image" src="https://user-images.githubusercontent.com/14901038/109232110-9b4b8580-777c-11eb-9eae-6ef01db766cd.png">

After quit/relaunch:
<img width="191" alt="image" src="https://user-images.githubusercontent.com/14901038/109232142-ae5e5580-777c-11eb-8011-00f78ee6bb82.png">

**Comment by exelban** [comment] 2021-02-25 23:20
Duplicate of #358

**Closed by exelban** 2021-02-25 23:20 UTC
