### ISSUE TITLE
Combine multiple monitoring items

### ISSUE THREAD

**Issue by mrbruce516** [exelban/stats#528] opened 2021-07-05 16:09 UTC
**Describe the bug**
It's not a bug, it's a functional requirement

**Details:**
On the menu bar there're too many icon, I wan't to combine multiple monitoring items into one item.
When I click on an item, the detailed information of multiple indicator items can be displayed. Just like istat menus

thanks developer! stats is really great so that I replaced istat menus haha
thanks a lot

**Comment by exelban** [comment] 2021-07-05 16:45
Duplicate of #500

**Closed by exelban** 2021-07-05 16:45 UTC
