### ISSUE TITLE
Feature request: Change the arrow color of the network stats to white

### ISSUE THREAD

**Issue by simonerancati** [exelban/stats#446] opened 2021-04-29 10:31 UTC
**Describe the feature**
I would like a setting to change the arrow color of the network stats to be always white so I can have only the white color in the menu bar.
<img width="611" alt="Schermata 2021-04-29 alle 12 23 12" src="https://user-images.githubusercontent.com/50338985/116537653-ca9a8200-a8e6-11eb-80f1-adc7d1565188.png">

**Details:**
 - Device: MacBook Air M1
 - MacOS 11.2.3
 - Application version 2.5.11

**Comment by exelban** [comment] 2021-04-29 10:52
Duplicate of #364

**Closed by exelban** 2021-04-29 10:52 UTC
