### ISSUE TITLE
[Bug] wrong cpu core temperature

### ISSUE THREAD

**Issue by Icarus-Xu** [exelban/stats#172] opened 2020-11-19 04:20 UTC
**Describe the bug**
i7-9750h has 6 cores but the display shows core #2-7 (should be #0-5 i think), and there is another core #9 and its temperature is 129 degrees, i guess it's not correct

**Details:**
 - Device: [Macbook Pro 16inch late 2019]
 - MacOS [11.1 Beta 20C5048k]
 - Application version [2.4.3]

**Comment by Icarus-Xu** [comment] 2020-11-19 04:24
<img width="282" alt="Screen Shot 2020-11-19 at 12 14 03 PM" src="https://user-images.githubusercontent.com/11155311/99621175-2c1a1300-2a62-11eb-8204-37a30082481f.png">

**Comment by Military-Doctor** [comment] 2020-11-19 04:41
Hello, I have the same bug.

Check the issue #170 for more details.

**Comment by Icarus-Xu** [comment] 2020-11-19 04:59
@Military-Doctor thanks for replying, i will check them out

**Comment by exelban** [comment] 2020-11-19 07:40
Duplicate of #150

**Closed by exelban** 2020-11-19 07:40 UTC
