### ISSUE TITLE
Authentication needed for every fan RPM change

### ISSUE THREAD

**Issue by LostInCompilation** [exelban/stats#1173] opened 2022-11-14 17:39 UTC
**Describe the bug**
Since about 3 or 4 releases Stats asks me for a password every time I change the fan RPM in manual mode. Before I just needed to enter the password once when switching to manual fan mode and was able to change the RPM without re-authentication. I also need to reenter the password when switching the second fan to manual or when switching them back to automatic.
However back then I was also running macOS 12. So I cannot rule out if macOS 13 is a factor here.

**Details:**
 - Device: MacBook Pro 2021 16" (M1 Pro)
 - macOS: macOS 13.0.1 (22A400)
 - Application version: 2.7.43 (Bug present since at least 2.7.41)

**Comment by exelban** [comment] 2022-11-14 18:28
Hi. Thanks for the feedback.
Please try to install 2.7.40 and check if it will ask for a password every time.

**Comment by exelban** [comment] 2022-11-15 15:25
Looks like it's similar to the #1166

**Comment by Moulick** [comment] 2022-11-15 15:26
Yep, this is exactly what I experienced.

**Comment by exelban** [comment] 2022-11-15 15:28
It's a very interesting bug. Because if I run the app via xcode it works normally. But after the build, I issue the same bug.

**Comment by Moulick** [comment] 2022-11-15 15:33
iStat menus is able to do control the fans just fine. The same version was able to control the fans in both Montrey and Ventura

**Comment by exelban** [comment] 2022-11-15 15:42
Yeap, I can confirm that it issues only new macOS 13.0.1

**Comment by exelban** [comment] 2022-11-15 18:08
Ok, I figured out why it does not work. The problem is the way how I ask for permission. I do that throw apple script (yeah, it's not the best way, but it works). And looks like this way stops working.
Looks like I need to implement an authorization service to make it work.

If it's important for you to control the fans you can run:
```
sudo /usr/sbin/chown root:admin /Applications/Stats.app/Contents/Resources/smc
sudo /bin/chmod 6555 /Applications/Stats.app/Contents/Resources/smc
```

After that Stats could control the fans.

PS: I'm not sure that it will be fixed this week, but I will try to do that.

**Comment by Moulick** [comment] 2022-11-16 10:52
yep, after the above it was able to control the speed but still it asked for the password 6 times

**Comment by Moulick** [comment] 2022-11-20 12:21
I just tried the 2.7.45 release. It asked for the password 6 times, asking to install helper, and still did not change the fan speed :)

**Comment by exelban** [comment] 2022-11-20 12:36
Yeap, notice that. I revoke the last update for now.

**Comment by exelban** [comment] 2022-11-20 13:05
Ok, I have updated the release. There was a problem with signing the helper app. Now it works fine. And fans could be controlled.

**Closed by exelban** 2022-11-20 13:05 UTC
Labels: bug

**Comment by Moulick** [comment] 2022-11-20 14:38
Hmm, it works, but still asked for the password 4 times.

**Comment by exelban** [comment] 2022-11-20 14:40
Do you have 4 fans and enabled fans sync?

**Comment by Moulick** [comment] 2022-11-20 14:41
I have 2 fans with sync enabled

**Comment by exelban** [comment] 2022-11-20 14:42
Yeap, and I suppose you press the max speed button?

**Comment by Moulick** [comment] 2022-11-20 14:44
I pressed that snowflake-looking button on the extreme right. Dunno if that's full speed or 0 speed

**Comment by exelban** [comment] 2022-11-20 14:48
Yeap, it's a reason why you have been asked 4 times: 2 times for mode change, and after 2 times for speed change.

You could normally deny after the first time because the helper is already installed. I will fix this when will have time to rewrite these views. It's not critical and now for password Stats will ask only when first time manipulating the fans.
