### ISSUE TITLE
No Sensors For MacBook Pro M1

### ISSUE THREAD

**Issue by AyAyRON123** [exelban/stats#276] opened 2021-01-06 06:30 UTC
**Describe the bug**
When opening the application there is no sensors option.
<img width="749" alt="Screen Shot 2021-01-06 at 2 43 20 pm" src="https://user-images.githubusercontent.com/76608972/103737646-87618e00-502d-11eb-9e9d-553aaa0ec9b0.png">

**Details:**
 - Device: MacBook Pro M1 2020
 - MacOS 11.1.0
 - Application version: 2.4.11

**Comment by exelban** [comment] 2021-01-06 10:18
Duplicate of #210

**Closed by exelban** 2021-01-06 10:18 UTC
